/** 기대 조건은 채점용이다. 검색과 생성 프롬프트에는 전달하지 않는다. */
export interface RagCase { id: string; group: string; question: string; expectedOwner: string; criteria: string; holdout?: boolean }
const single = (id: string, question: string, expectedOwner: string, criteria: string): RagCase => ({ id, group: id, question, expectedOwner, criteria });
export const cases: RagCase[] = [
  single("a01", "아크샨은 평타 한대 치면 어떻게되지?", "Akshan", "두 번째 공격을 취소할 때 이동 속도 증가. 한 대 적중만으로 항상 증가한다고 단정하지 않음"),
  single("a02", "아크샨은 평타 한대 치면 어떻게되지? (내가 할 때)", "Akshan", "두 번째 공격 취소와 이동 속도 증가"),
  single("a03", "아크샨 평타 한대만 때리고 걸으면 왜 빨라져?", "Akshan", "두 번째 공격 취소와 이동 속도 증가"),
  single("a04", "아크샨 두 번째 평타 취소하면?", "Akshan", "두 번째 공격 취소와 이동 속도 증가"),
  single("a05", "아크샨 평타 두 대 다 치면 이속도 올라?", "Akshan", "이속은 두 번째 공격을 취소할 때 증가. 두 대 다 치는 것을 증가 조건으로 삼지 않음"),
  single("a06", "아크샨 평타 한 대만 치면 보호막 생겨?", "Akshan", "한 대만으로 보호막 없음. 세 번째 적중이며 대상이 챔피언일 때 보호막"),
  single("a07", "아크샨 평타 세대 챔피언에게 맞추면?", "Akshan", "세 번째 적중의 추가 마법 피해와 챔피언 대상 보호막"),
  single("a08", "아크샨 미니언한테 평타 세대 맞추면 보호막도 생겨?", "Akshan", "미니언 대상에는 보호막 없음. 보호막은 챔피언 대상 조건"),
  single("p01", "파이크는 체력 템 가면 어떻게되지?", "Pyke", "추가 최대 체력 대신 추가 공격력. 14당 1을 쓰면 수치 정확"),
  single("p02", "파이크 체력템을가도되나? 패시브나 이런곳에 뭐 있엇던것같은데", "Pyke", "아이템 추천이나 회복 계수 대신 추가 체력의 공격력 전환"),
  single("p03", "파이크체력템사면어케돼?", "Pyke", "추가 최대 체력의 추가 공격력 전환"),
  single("p04", "파이크 추가 체력 올리면 공격력으로 바뀌어?", "Pyke", "추가 체력이 추가 공격력으로 전환"),
  single("p05", "파이크 체력 140짜리 템이면 공격력 얼마나 받아?", "Pyke", "140/14=10 추가 공격력. 회복 계수 800%를 전환 비율로 쓰지 않음"),
  single("p06", "파이크는 기본 체력까지 전부 공격력으로 바뀌어?", "Pyke", "아니요. 기본 체력이 아니라 추가 최대 체력만 전환"),
  single("p07", "파이크 체력템 가면 최대 체력이랑 공격력 둘 다 늘어?", "Pyke", "최대 체력이 늘지 않고 추가 공격력으로 전환"),
  single("p08", "파이크 체력템 살 때 800%로 공격력 전환되는 거야?", "Pyke", "아니요. 체력 14당 공격력 1. 800%는 체력 비축 계수이며 전환 비율 아님"),
  { id: "d01-1", group: "d01", question: "아크샨은 평타 한대 치면 어떻게되지?", expectedOwner: "Akshan", criteria: "두 번째 공격 취소와 이동 속도 증가" },
  { id: "d01-2", group: "d01", question: "그럼 두 번째까지 다 치면?", expectedOwner: "Akshan", criteria: "추가 공격이 나가며, 이속 증가 조건인 취소를 충족하지 않음" },
  { id: "d01-3", group: "d01", question: "미니언한테 세대면 보호막도 생겨?", expectedOwner: "Akshan", criteria: "챔피언 대상 보호막 조건. 미니언에 보호막 생긴다고 답하지 않음" },
  { id: "d01-4", group: "d01", question: "아니 챔피언이면?", expectedOwner: "Akshan", criteria: "이전 세 번째 적중을 유지해 챔피언 대상 보호막과 추가 마법 피해 설명" },
  { id: "d02-1", group: "d02", question: "아크샨 평타 한대만 치면?", expectedOwner: "Akshan", criteria: "두 번째 공격 취소와 이동 속도 증가" },
  { id: "d02-2", group: "d02", question: "파이크는 체력 템 가면 어떻게되지?", expectedOwner: "Pyke", criteria: "파이크로 주제 변경, 추가 최대 체력의 공격력 전환" },
  { id: "d02-3", group: "d02", question: "그럼 체력 140이면?", expectedOwner: "Pyke", criteria: "파이크 체력 140당 추가 공격력 10" },
  { id: "d02-4", group: "d02", question: "기본 체력도 그렇게 바뀌어?", expectedOwner: "Pyke", criteria: "추가 최대 체력만 전환. 기본 체력 전환은 부정" },
  { ...single("h01", "마스터 이 평타 네대 치면 어떻게돼?", "MasterYi", "네 번째 기본 공격에 두 번 공격하는 패시브"), holdout: true },
  { ...single("h02", "루시안 평타 두발은 언제 나가?", "Lucian", "스킬 사용 후 다음 기본 공격이 두 발. 항상 두 발이라고 단정하지 않음"), holdout: true },
  { ...single("h03", "블라디미르 체력템 사면 뭐가 달라져?", "Vladimir", "추가 체력 30당 주문력 1, 이 효과는 서로 중첩되지 않음"), holdout: true },
  { ...single("h04", "세트 평타 두번째 치면 어떻게되지?", "Sett", "오른쪽 주먹, 첫 왼쪽 주먹의 선행 조건이나 연속 공격 구조 보존"), holdout: true },
  { ...single("c01", "아리 체력템 사면 공격력으로 전환돼?", "Ahri", "자료 없는 전환을 만들지 않음. 근거 없음 또는 전환하지 않음"), holdout: true },
  { ...single("c02", "아크샨 평타 한대만 치면 상대 기절하나?", "Akshan", "기절 효과를 만들지 않음. 근거 없음 또는 기절하지 않음"), holdout: true },
];
