"""로컬 공식 역할군과 정규화 기본 능력치를 독립 시안으로 내보낸다."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
version = json.loads((ROOT / "public/data/version.json").read_text())
patch = version["patchVersion"]
cards = json.loads((ROOT / f"public/data/{patch}/llm/champion-cards-ko_KR.json").read_text())["cards"]
champions = []
for card in cards:
    source = json.loads((ROOT / f"public/data/{patch}/champions/ko_KR/{card['id']}.json").read_text())["champion"]
    champions.append({"id": card["id"], "name": card["name"], "roles": card["roleTags"],
                      "stats": source["baseStats"]})
data = {"patch": patch, "ddragon": version["sources"]["ddragon"], "champions": champions}
(HERE / "champions.js").write_text("// Generated by generate.py\nglobalThis.rankingData = " +
                                  json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
print(f"순위 시안 데이터: {len(champions)}명, 패치 {patch}")
