import { expect, test } from "@playwright/test";
import { waitForModelFreeInput } from "./support/advisor";

for (const width of [390, 1280]) test(`실사용 오류의 문맥·표시 회귀: ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto("./");
  await page.getByRole("button", { name: "챔피언 추가하기", exact: true }).click();
  await page.getByRole("button", { name: "Select 오공", exact: true }).click();
  await page.getByRole("button", { name: "챔피언 선택기 닫기", exact: true }).click();
  await page.getByRole("button", { name: "롤 지식 도우미 열기", exact: true }).click();
  const input = page.getByRole("textbox", { name: "롤 질문 입력", exact: true });
  await waitForModelFreeInput(page, input, page.getByRole("button", { name: "모델 없이 써보기", exact: true }));
  const copies = page.getByRole("button", { name: "답변 복사", exact: true });
  const latest = () => copies.last().locator("..").locator("..");
  async function ask(question: string) {
    const count = await copies.count();
    await input.fill(question);
    await page.getByRole("button", { name: "보내기", exact: true }).click();
    await expect(copies).toHaveCount(count + 1);
    await expect(page.getByRole("button", { name: "중단", exact: true })).toBeHidden();
    return latest();
  }
  await ask("아크샨 평타 한 방 치고 두 번째 안 쏘면?");
  await expect(latest()).toContainText("추가 공격 속도");
  await expect(latest()).not.toContainText("Move Speed");
  await expect(page.getByText(/세 번 적중할 때마다 추가 물리 피해/).filter({ visible: true })).toHaveCount(0);
  await ask("그럼 두 발 전부 쏠게. 이속 생겨?");
  await expect(latest()).toContainText("취소 조건에 해당하지");
  await ask("그럼 평타 세대 맞추면?");
  await expect(latest()).toContainText("마법 피해");
  await expect(latest()).toContainText("보호막");
  await expect(latest()).not.toContainText("취소 조건에 해당하지");
  await ask("그럼 평타 한 대만 맞추면?");
  await expect(latest()).toContainText("1회 적중은 이 효과의 3회 적중 조건에 해당하지");
  await expect(latest()).not.toContainText("이동 속도를 얻");
  await page.getByRole("button", { name: "새 대화", exact: true }).click();
  await ask("파이크가 체력 70짜리 아이템 두 개 사면 공격력 얼마나 늘어?");
  await ask("아 아니 추가 체력 42로 정정할게");
  await expect(latest()).toContainText("공격력 3");
  await ask("방어력 100 상대로 방관 30%에 고정 방관 10이면 최종 방어력?");
  await expect(latest()).toContainText("= 60");
  await ask("아리 6레벨 방어력과 마법 저항력 알려줘");
  await ask("How should I lane as Ahri against Fizz?");
  await expect(latest()).toContainText("피즈");
  await expect(latest()).not.toContainText("방어력 (6레벨)");
  const savedCount = await copies.count();
  await page.reload();
  await page.getByRole("button", { name: "롤 지식 도우미 열기", exact: true }).click();
  await expect(copies).toHaveCount(savedCount);
  await ask("가랜 6렙 방어력이랑 마저 좀");
  await expect(latest()).toContainText("가렌");
  await expect(latest()).not.toContainText("오공");
  await ask("장화 가격은?");
  await expect(latest()).toContainText("300 골드");
  await ask("오공 문도 체력 비교");
  await ask("체력회복량은 둘다 어떻게되지?");
  await ask("아니 체력도 같이");
  await expect(latest()).toContainText("오공");
  await expect(latest()).toContainText("문도");
  await expect(latest()).not.toContainText("아리");
});
